[build]
publish = "public"
command = "hugo --gc --minify"
HUGO_ENABLEGITINFO = "true"
HUGO_VERSION = "0.80.0"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_ENV = "deploy"

[context.branch-deploy.environment]
HUGO_ENV = "development"
